<h1>Órdenes Ordinarias</h1>
<section>
    <table>
        <thead>
            <tr>
                <th>Número</th>
                <th>Cantidad</th>
                <th>Tipo</th>
                <th>Prioridad</th>
                <th>Estado</th>
                <th>Opciones</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>10</td>
                <td>Orden</td>
                <td>Alta</td>
                <td>Finalizada</td>
                <td>Editar</td>
            </tr>
            <tr>
                <td>2</td>
                <td>50</td>
                <td>Orden</td>
                <td>Baja</td>
                <td>Pendiente</td>
                <td>Editar</td>
            </tr>
            <tr>
                <td>3</td>
                <td>20</td>
                <td>Orden</td>
                <td>Media</td>
                <td>Pendiente</td>
                <td>Editar</td>
            </tr>
        </tbody>
    </table>
</section>